description:	'An introductory course on Computational Linguistics'
title:          'Computational Linguistics'
url:            'https://jcbgamboa.github.io/computational_linguistics'
baseurl:        '/'
